id: d0ec4e25ff4344bc8b566d05d803409e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_286-The_Dedication_Protecting_All_Beings-v2
  language: en
  author: ''
  volume: {}
